# Document-generation determinism check.
#
# Given two .docx files generated from the same wizard inputs, this script
# verifies they are byte-for-byte identical at the document-content level
# (word/document.xml, headers, footers). Variable elements (timestamps in
# docProps, revision IDs, custom XML rsids) are normalised before comparison.
#
# A clean pass is required before release: identical inputs must produce
# identical outputs, otherwise audit reproducibility is impossible.
#
# Usage:
#   .\tests\check-determinism.ps1 -First <path1.docx> -Second <path2.docx>
#
# Exit code 0 if the two files are content-equivalent; 1 otherwise.

param(
    [Parameter(Mandatory = $true)]
    [string]$First,
    [Parameter(Mandatory = $true)]
    [string]$Second
)

Add-Type -AssemblyName System.IO.Compression.FileSystem

function Get-DocxNormalisedContent {
    param([string]$DocxPath)
    if (-not (Test-Path $DocxPath)) {
        throw "File not found: $DocxPath"
    }
    $zip = [System.IO.Compression.ZipFile]::OpenRead($DocxPath)
    try {
        $out = @{}
        foreach ($entry in $zip.Entries) {
            $name = $entry.FullName
            # Skip metadata files whose contents legitimately differ across runs.
            # docProps/core.xml has dcterms:created and dcterms:modified that
            # update per generation even when the inputs are identical.
            if ($name -eq "docProps/core.xml") { continue }
            # Also skip app.xml — has TotalTime, Pages etc. that Word may
            # recompute. Both are scrubbed for identity but stylistic.
            if ($name -eq "docProps/app.xml") { continue }
            $stream = $entry.Open()
            $reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8)
            $content = $reader.ReadToEnd()
            $reader.Close()
            # Strip Word rsid attributes (random per session/save).
            $content = [regex]::Replace($content, '\sw:rsidR="[^"]*"', '')
            $content = [regex]::Replace($content, '\sw:rsidRDefault="[^"]*"', '')
            $content = [regex]::Replace($content, '\sw:rsidP="[^"]*"', '')
            $content = [regex]::Replace($content, '\sw:rsidRPr="[^"]*"', '')
            $content = [regex]::Replace($content, '\sw:rsidTr="[^"]*"', '')
            $content = [regex]::Replace($content, '\sw14:paraId="[^"]*"', '')
            $content = [regex]::Replace($content, '\sw14:textId="[^"]*"', '')
            # Strip the "Generated on {date}" line we inject — the date naturally
            # differs between runs. Match the wider footer disclaimer paragraph
            # that buildFooterDisclaimer() produces.
            $content = [regex]::Replace(
                $content,
                'Generated by Legal AML Starter Kit Assistant[^<]*?on \d{1,2}/\d{1,2}/\d{4}',
                'Generated by Legal AML Starter Kit Assistant [NORMALISED]'
            )
            $out[$name] = $content
        }
        return $out
    } finally {
        $zip.Dispose()
    }
}

Write-Host "Reading: $First"
$a = Get-DocxNormalisedContent -DocxPath $First
Write-Host "Reading: $Second"
$b = Get-DocxNormalisedContent -DocxPath $Second

$keysA = [System.Collections.Generic.HashSet[string]]::new()
$keysB = [System.Collections.Generic.HashSet[string]]::new()
foreach ($k in $a.Keys) { [void]$keysA.Add($k) }
foreach ($k in $b.Keys) { [void]$keysB.Add($k) }

$onlyInA = $keysA | Where-Object { -not $keysB.Contains($_) }
$onlyInB = $keysB | Where-Object { -not $keysA.Contains($_) }
$common = $keysA | Where-Object { $keysB.Contains($_) }

$diffs = New-Object System.Collections.Generic.List[string]
foreach ($k in $onlyInA) { $diffs.Add("only in first: $k") }
foreach ($k in $onlyInB) { $diffs.Add("only in second: $k") }
foreach ($k in $common) {
    if ($a[$k] -ne $b[$k]) {
        $diffs.Add("content differs: $k")
    }
}

Write-Host ""
if ($diffs.Count -eq 0) {
    Write-Host "DETERMINISTIC — both files have identical content after normalisation."
    exit 0
} else {
    Write-Host "DIVERGENT — $($diffs.Count) difference(s):" -ForegroundColor Red
    foreach ($d in $diffs) {
        Write-Host "  $d" -ForegroundColor Red
    }
    exit 1
}
